version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - minio_network

  mc:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./etl_scripts:/etl_scripts
    entrypoint: >
      /bin/sh -c "
      while ! mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
        sleep 1;
      done;
      mc mb --ignore-existing myminio/my-bucket &&
      mc cp /etl_scripts/titanic.csv myminio/my-bucket/titanic.csv
      "
    networks:
      - minio_network

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.15.0
    container_name: mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow
    command: /usr/local/bin/mlflow server --backend-store-uri sqlite:///mlruns.db --default-artifact-root s3://mlflow --host 0.0.0.0
    networks:
      - minio_network

networks:
  minio_network:
    driver: bridge
