version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  mc:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./etl_scripts:/etl_scripts
    entrypoint: >
      /bin/sh -c "
      while ! mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
        sleep 1;
      done;
      mc mb --ignore-existing myminio/my-bucket &&
      mc cp /etl_scripts/titanic.csv myminio/my-bucket/titanic.csv
      "
